#!/bin/bash
export IFS=$'\n'

CMDNAME=`basename $0`

##
usage_exit(){
        echo "Usage : ${CMDNAME} [-d:create directory] [directory | archive file]"
        exit 1
}

if [ $# -eq 0 ] ; then
	usage_exit
fi

CREATE_DIR=false

## http://takuya-1st.hatenablog.jp/entry/2015/12/24/234238
while getopts "dh" OPT ; do
        case $OPT in
                d)
                        CREATE_DIR=true
                ;;
                h)
                        usage_exit
                ;;
        esac
done
shift $(($OPTIND - 1))

if [ $# -eq 0 ] ; then
        usage_exit
fi

for file in `find ${1} -iname "*.zip" -o -iname "*.rar" -o -iname "*.gz" -o -iname "*.7z" -o -iname "*.tar" -o -iname "*.tgz" -o -iname "*.bz2" -o -iname "*.xz"` ; do
	ext=${file##*.}
	ext_lc=${ext,,}

	if "${CREATE_DIR}"; then
		case "$ext_lc" in
			"zip" ) unzip ${file} -d ${file%%.zip}/ ;;
			"rar" ) unrar x ${file} ${file%%.rar}/ ;;
			"gz" ) gzip -d ${file} ;;
			"7z" ) 7z x ${file} -o${file%%.7z} ;;
			"tar" ) tar -xvf ${file} --directory=${file%%.tar}/ ;;
        	        "tgz" ) tar -xvf ${file} --directory=${file%%.tgz}/ ;;
        	        "bz2" ) tar -xvf ${file} --directory=${file%%.bz2}/ ;;
        	        "xz" ) tar -xvf ${file} --directory=${file%%.xz}/ ;;
		esac
	else
                case "$ext_lc" in
                        "zip" ) unzip ${file} ;;
                        "rar" ) unrar x ${file} ;;
                        "gz" ) gzip -d ${file} ;;
                        "7z" ) 7z x ${file} ;;
                        "tar" ) tar -xvf ${file} ;;
                        "tgz" ) tar -xvf ${file} ;;
                        "bz2" ) tar -xvf ${file} ;;
                        "xz" ) tar -xvf ${file} ;;
                esac
	fi

done

exit 0
